# Generated by Django 2.1.4 on 2019-03-22 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cour_id', models.CharField(max_length=15, verbose_name='学生ID')),
                ('course', models.CharField(max_length=30, verbose_name='课程')),
                ('grade', models.IntegerField(default=60, verbose_name='分数')),
            ],
            options={
                'db_table': 'course',
            },
        ),
        migrations.CreateModel(
            name='StudentInformationModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=15, verbose_name='学生ID')),
                ('stu_name', models.CharField(max_length=30, verbose_name='学生姓名')),
                ('stu_phone', models.CharField(max_length=20, verbose_name='学生电话')),
                ('str_addr', models.TextField(verbose_name='学生地址')),
                ('stu_faculty', models.CharField(max_length=20, verbose_name='院系')),
                ('stu_major', models.CharField(max_length=30, verbose_name='专业')),
            ],
            options={
                'db_table': 'studentinformation',
            },
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_id', models.CharField(max_length=15, verbose_name='学生ID')),
                ('username', models.CharField(max_length=10, verbose_name='用户名')),
                ('password', models.CharField(max_length=10, verbose_name='密码')),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
